services:

  session_db:
    image: redis:7.2-alpine

    container_name: redis_db

    command: redis-server --save 60 1 --loglevel warning

    volumes:
      - redis_data:/data

  postgres_db:
    image: postgres:16-alpine

    container_name: postgres_db

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      REDIS_HOST: session_db
      REDIS_PORT: 6379

      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}

      DB_HOST: postgres_db
      DB_PORT: 5432

    depends_on:
      postgres_db:
        condition: service_healthy
      rag:
        condition: service_healthy
      stt:
        condition: service_healthy
      tts:
        condition: service_healthy
      NLU_Router:
        condition: service_healthy
      action_handler:
        condition: service_healthy
      ollama:
        condition: service_healthy
  
  rag:
    build:
      context: ./RAG
      dockerfile: Dockerfile

    depends_on:
      - ollama

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5  
  tts:
    build:
      context: ./TTS
      dockerfile: Dockerfile

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
  
  stt:
    build:
      context: ./STT
      dockerfile: Dockerfile

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
  
  NLU_Router:
    build:
      context: ./NLU_Router
      dockerfile: Dockerfile

    depends_on:
      - ollama

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
  
  action_handler:

    build:
      context: ./Action_handler
      dockerfile: Dockerfile

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    build: 
      context: ./Ollama
      dockerfile: Dockerfile

    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5

    extra_hosts:
      - "host.docker.internal_host-gateway"

volumes:
  redis_data:
  postgres_data: